# Generated by Django 2.1.10 on 2019-07-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designation_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('client_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('contact', models.CharField(blank=True, max_length=10)),
                ('emp_id', models.CharField(max_length=15, null=True)),
                ('slack_id', models.CharField(blank=True, max_length=70)),
                ('image_url', models.CharField(blank=True, max_length=250)),
                ('hobbies', models.CharField(blank=True, max_length=250)),
                ('bio', models.CharField(blank=True, max_length=1100)),
                ('git_id', models.CharField(blank=True, max_length=100)),
                ('link_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDesignation',
            fields=[
                ('client_id', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('designation', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLanguage',
            fields=[
                ('client_id', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('language', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLocation',
            fields=[
                ('client_id', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProject',
            fields=[
                ('client_id', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('current_project', models.CharField(blank=True, max_length=50)),
                ('previous_project', models.CharField(blank=True, max_length=300)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('client_id', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('skill', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hierarchy',
            fields=[
                ('client_id', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('manager_id', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
